/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic_PreprocessMessages = require('./code/customermessage-logic-preprocessMessages');
const productfaq_Logic_EmbedFAQ = require('./code/productfaq-logic-embedFAQ');
const customermessage_Logic_GenerateReply = require('./code/customermessage-logic-generateReply');
const customermessage_Logic_MaintainSO = require('./code/customermessage-logic-maintainSO');
const customertickets_uploadFiles = require('./code/customertickets-uploadFiles');
const customertickets_deleteUploadedFiles = require('./code/customertickets-deleteFiles');
const customerattachments_onread = require('./code/customerattachments-onRead');
const customertickets_beforeCreate = require('./code/customertickets-beforeCreate');
const userinfo = require('./code/userinfo');
class monicaSanchez_1_H04Srv extends LCAPApplicationService {
    async init() {
        this.after(['CREATE', 'UPDATE'], 'ProductFAQ', async (results, request) => {
            await productfaq_Logic_EmbedFAQ(results, request);
        });

        this.on('Action1', 'CustomerMessage', async (request) => {
            return customermessage_Logic_GenerateReply(request);
        });

        this.on('Action2', 'CustomerMessage', async (request, next) => {
            return customermessage_Logic_MaintainSO(request, next);
        });

        this.after(['CREATE', 'UPDATE'], 'customerTickets', async (request) => {
            await customermessage_Logic_PreprocessMessages(request);
        });

        this.on('uploadAttachmentCustomerMessage', async (request) => {
            await customertickets_uploadFiles(request);
        });

        this.on('deleteAttachmentCustomerMessage', async (request) => {
            await customertickets_deleteUploadedFiles(request);
        });
        this.on('READ', 'CustomerMessagesAttachments', async (request, next) => {
            return customerattachments_onread(request, next);
        });

        this.before('CREATE', 'customerTickets', async request => {
            await customertickets_beforeCreate(request);
        });

        this.on('userInfo', async(request) => {
            return userinfo(request);
        });



        return super.init();
    }
}


module.exports = {
    monicaSanchez_1_H04Srv
};