/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic_PreprocessMessages = require('./code/customermessage-logic-preprocessMessages');
const productfaq_Logic_EmbedFAQ = require('./code/productfaq-logic-embedFAQ');
const customermessage_Logic_GenerateReply = require('./code/customermessage-logic-generateReply');
const customermessage_Logic_MaintainSO = require('./code/customermessage-logic-maintainSO');

class monicaSanchez_1_H04Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessage', async (request) => {
            await customermessage_Logic_PreprocessMessages(request);
        });

        this.after(['CREATE', 'UPDATE'], 'ProductFAQ', async (results, request) => {
            await productfaq_Logic_EmbedFAQ(results, request);
        });

        this.on('Action1', 'CustomerMessage', async (request) => {
            return customermessage_Logic_GenerateReply(request);
        });

        this.on('Action2', 'CustomerMessage', async (request, next) => {
            return customermessage_Logic_MaintainSO(request, next);
        });

        this.after(['CREATE', 'UPDATE'], 'customerTickets', async (request) => {
            await customermessage_Logic_PreprocessMessages(request);
        });

        this.before('CREATE', 'customerTickets', async request => {
            const customerTicketID = request.data.ID;
            if (!customerTicketID) {
                return request.reject(400, 'CustomerTicket ID is missing.');
            }

            let customerTicketEntry;
            try {
                // Fetch the specific CustomerMessage entry for update
                customerTicketEntry = await SELECT.one('MonicaSanchez_1_H04.CustomerMessage').orderBy({ ref: ['customerMessageID'], sort: 'desc' });
                if (!customerTicketEntry) {
                    return request.reject(404, `CustomerMessage with ID ${customerTicketEntry} not found.`);
                }
                request.data.customerId = "C004";
                request.data.originatingCountry = "Spain";
                request.data.sourceLanguage = "Spanish";
                request.data.customerName = "Prueba";
                request.data.customerMessageID = customerTicketEntry.customerMessageID + 1;
               // await UPDATE('customerTickets').set('customerMessageID', request.data.customerMessageID);
            } catch (error) {
                return request.reject(500, error);
            }
        });

        

        return super.init();
    }
}


module.exports = {
    monicaSanchez_1_H04Srv
};